import {createGame, capacities, investigate, treat, admit, discharge, buy, endRound} from './engine.js';
import {STAFF,FACILITIES,MARKET} from './data.js';
let game=createGame(); let selected=null;
const $=id=>document.getElementById(id); const names={nursing:'Nursing',medication:'Medication',surgery:'Surgery'};
function render(){const cap=capacities(game);$('stats').innerHTML=stat('Round',game.round)+stat('Reputation',game.reputation)+stat('Money','$'+game.money);$('edCapacity').textContent=`${game.ed.length} / ${cap.ed}`;$('wardCapacity').textContent=`${game.ward.length} / ${cap.ward} beds`;$('briefing').innerHTML=`<strong>Round ${game.round}</strong><span>Investigate patients, build your treatment engine, and discharge safely before ending the round.</span>`;$('resources').innerHTML=Object.entries(game.resources).map(([k,v])=>`<span class="resource-pill ${k}">${names[k]} ${v}</span>`).join('');$('ed').innerHTML=cards(game.ed,'ed',cap.ed);$('ward').innerHTML=cards(game.ward,'ward',cap.ward);$('staff').innerHTML=game.staff.map((k,i)=>engineCard(STAFF[k],game.usedStaff.includes(i))).join('');$('facilities').innerHTML=game.facilities.map(k=>engineCard(FACILITIES[k])).join('');$('market').innerHTML=MARKET.map(m=>marketCard(m)).join('');$('log').innerHTML=game.log.slice(0,8).map(x=>`<li>${x}</li>`).join('');$('endTurn').disabled=game.gameOver;bind();}
function cards(items,place,capacity){return items.map(p=>patientCard(p,place)).join('')+Array.from({length:Math.max(0,capacity-items.length)},()=>`<div class="empty-slot">Empty ${place==='ward'?'bed':'space'}</div>`).join('')}
function patientCard(p,place){const needs=p.revealed?Object.entries(p.needs).filter(([,n])=>n).flatMap(([k,n])=>Array.from({length:n},(_,i)=>`<span class="need ${k} ${i<(p.completed[k]||0)?'done':''}">${names[k]}</span>`)).join(''):`<span class="need unknown">Needs hidden</span>`;let actions='';if(!p.revealed)actions=`<button data-action="investigate" data-id="${p.id}">Investigate</button>`;else{actions=Object.keys(names).filter(k=>(p.completed[k]||0)<p.needs[k]).map(k=>`<button data-action="treat" data-type="${k}" data-id="${p.id}" ${game.resources[k]<1||(k==='nursing'&&p.nursingRound===game.round)?'disabled':''}>${names[k]}</button>`).join('');if(place==='ed'&&p.wardRequired)actions+=`<button data-action="admit" data-id="${p.id}">Admit</button>`;actions+=`<button data-action="discharge" data-id="${p.id}">Discharge</button>`}return `<article class="patient-card ${selected===p.id?'selected':''}" data-select="${p.id}"><div class="portrait">${p.portrait}</div><div class="card-title">Patient ${p.portrait}</div><div class="card-subtitle">${p.revealed?`Reward $${p.reward} · Rep +${p.reputation}`:'Awaiting assessment'}</div><div class="needs">${needs}</div>${p.revealed&&p.wardRequired?'<div class="ward-tag">Ward discharge required</div>':''}<div class="patient-actions">${actions}</div></article>`}
function engineCard(x,used=false){return `<article class="game-card ${used?'used':''}"><div class="icon">${x.icon}</div><div class="card-title">${x.name}</div><p class="effect">${x.effect}</p>${used?'<p class="ward-tag">Used this round</p>':''}</article>`}function marketCard(m){const x=m.kind==='staff'?STAFF[m.key]:FACILITIES[m.key];return `<article class="market-card"><div class="icon">${x.icon}</div><div class="card-title">${x.name}</div><p class="effect">${x.effect}</p><button data-action="buy" data-kind="${m.kind}" data-key="${m.key}" ${game.money<x.cost?'disabled':''}>Buy · $${x.cost}</button></article>`}function stat(k,v){return `<span class="stat">${k} ${v}</span>`}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const {action,id,type,kind,key}=b.dataset;const ok=action==='investigate'?investigate(game,id):action==='treat'?treat(game,id,type):action==='admit'?admit(game,id):action==='discharge'?discharge(game,id):buy(game,kind,key);if(!ok)toast('That action is not available yet.');render()});document.querySelectorAll('[data-select]').forEach(c=>c.onclick=()=>{selected=c.dataset.select;render()})}
$('endTurn').onclick=()=>{endRound(game);render()};$('reset').onclick=()=>{game=createGame(Date.now()%1000);selected=null;render()};function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1500)}render();
