import {PATIENTS, STAFF, FACILITIES} from './data.js';

const clone = value => JSON.parse(JSON.stringify(value));
export function createGame(seed=1){
  const deck=shuffle(clone(PATIENTS),seed);
  const state={round:1,money:10,reputation:5,ed:[],ward:[],deck,discard:[],staff:['doctor','nurse','pharmacist'],facilities:['ed','ward'],usedStaff:[],resources:{nursing:0,medication:0,surgery:0},log:[],gameOver:false};
  drawPatients(state,2); startProduction(state); state.log.unshift('Round 1: two patients arrived in ED.'); return state;
}
export function capacities(s){return s.facilities.reduce((a,k)=>{const c=FACILITIES[k].capacity||{};a.ed+=(c.ed||0);a.ward+=(c.ward||0);return a},{ed:0,ward:0});}
export function startProduction(s){s.resources={nursing:0,medication:0,surgery:0};for(const k of s.staff){const x=STAFF[k];if(x.production&&(!x.requires||s.facilities.includes(x.requires)))add(s.resources,x.production)}for(const k of s.facilities)add(s.resources,FACILITIES[k].production||{});s.usedStaff=[];}
export function investigate(s,id){const p=find(s,id);if(!p||p.revealed)return false;const doctorIndex=s.staff.findIndex((k,i)=>k==='doctor'&&!s.usedStaff.includes(i));if(doctorIndex<0)return false;p.revealed=true;s.usedStaff.push(doctorIndex);s.log.unshift(`Patient ${p.portrait} investigated: needs revealed.`);return true;}
export function treat(s,id,type){const p=find(s,id);if(!p?.revealed||!['nursing','medication','surgery'].includes(type))return false;const done=p.completed[type]||0;if(done>=p.needs[type]||s.resources[type]<1)return false;if(type==='nursing'&&p.nursingRound===s.round)return false;s.resources[type]--;p.completed[type]=done+1;if(type==='nursing')p.nursingRound=s.round;s.log.unshift(`${label(type)} provided to patient ${p.portrait}.`);return true;}
export function admit(s,id){const c=capacities(s);const i=s.ed.findIndex(p=>p.id===id);if(i<0||!s.ed[i].revealed||s.ward.length>=c.ward)return false;s.ward.push(s.ed.splice(i,1)[0]);s.log.unshift(`Patient ${s.ward.at(-1).portrait} admitted to the ward.`);return true;}
export function discharge(s,id){const location=s.ward.some(p=>p.id===id)?s.ward:s.ed;const i=location.findIndex(p=>p.id===id);if(i<0)return false;const p=location[i];const complete=Object.keys(p.needs).every(k=>(p.completed[k]||0)>=p.needs[k]);if(!p.revealed||!complete||(p.wardRequired&&location===s.ed))return false;location.splice(i,1);s.money+=p.reward;s.reputation+=p.reputation;s.discard.push(p);s.log.unshift(`Patient ${p.portrait} discharged: +$${p.reward}, +${p.reputation} reputation.`);return true;}
export function buy(s,kind,key){const item=kind==='staff'?STAFF[key]:FACILITIES[key];if(!item||s.money<item.cost)return false;s.money-=item.cost;(kind==='staff'?s.staff:s.facilities).push(key);s.log.unshift(`${item.name} added for $${item.cost}. Production begins next round.`);return true;}
export function endRound(s){if(s.gameOver)return;deteriorate(s);s.round++;drawPatients(s,Math.min(2+Math.floor((s.round-1)/4),3));startProduction(s);if(s.reputation<=0){s.gameOver=true;s.log.unshift('The hospital has lost public confidence. Prototype over.');}else s.log.unshift(`Round ${s.round} begins.`);}
function deteriorate(s){for(const p of [...s.ed,...s.ward]){if(!p.revealed)continue;p.wait=(p.wait||0)+1;if(p.wait>=p.deterioratesAfter){p.wait=0;p.deteriorations=(p.deteriorations||0)+1;if(p.deteriorations>=2){removePatient(s,p.id);s.reputation=Math.max(0,s.reputation-2);s.log.unshift(`Patient ${p.portrait} died. -2 reputation.`)}else{p.needs.nursing++;s.log.unshift(`Patient ${p.portrait} worsened and gained a Nursing Care need.`)}}}}
function drawPatients(s,count){const cap=capacities(s).ed;for(let i=0;i<count;i++){if(!s.deck.length)break;if(s.ed.length>=cap){s.reputation=Math.max(0,s.reputation-1);s.log.unshift('ED full: an arriving patient was turned away. -1 reputation.');continue}const p=s.deck.shift();p.revealed=false;p.completed={nursing:0,medication:0,surgery:0};p.wait=0;p.deteriorations=0;s.ed.push(p)}}
function find(s,id){return [...s.ed,...s.ward].find(p=>p.id===id)}function removePatient(s,id){for(const a of [s.ed,s.ward]){const i=a.findIndex(p=>p.id===id);if(i>=0){a.splice(i,1);return}}}function add(a,b){for(const k of Object.keys(a))a[k]+=b[k]||0}function label(t){return t[0].toUpperCase()+t.slice(1)}
function shuffle(array,seed){let x=seed;for(let i=array.length-1;i>0;i--){x=(x*9301+49297)%233280;const j=Math.floor((x/233280)*(i+1));[array[i],array[j]]=[array[j],array[i]]}return array}
