import {PATIENTS, STAFF, FACILITIES} from './data.js?v=2';
const clone=value=>JSON.parse(JSON.stringify(value));

export function createGame(seed=1){
  const state={round:1,money:10,reputation:5,deck:shuffle(clone(PATIENTS),seed),discard:[],facilities:[],staff:[],resources:{medication:0,surgery:0},log:[],gameOver:false,nextId:1};
  const ed=addFacility(state,'ed'); const ward=addFacility(state,'ward');
  addStaff(state,'doctor',ed.id); addStaff(state,'nurse',ward.id); addStaff(state,'pharmacist',ed.id);
  drawPatients(state,2); startRound(state); state.log.unshift('Round 1: two patients arrived in Emergency.'); return state;
}

export function addFacility(state,key){const facility={id:`f${state.nextId++}`,key,patients:[],nursing:0};state.facilities.push(facility);return facility}
export function addStaff(state,key,facilityId=null){const member={id:`s${state.nextId++}`,key,facilityId,used:false};state.staff.push(member);return member}
export function getFacility(state,id){return state.facilities.find(f=>f.id===id)}
export function facilityDefinition(f){return FACILITIES[f.key]}
export function patientFacility(state,patientId){return state.facilities.find(f=>f.patients.some(p=>p.id===patientId))}

export function startRound(state){state.resources={medication:0,surgery:0};for(const f of state.facilities)f.nursing=0;for(const member of state.staff){member.used=false;const facility=getFacility(state,member.facilityId);if(!facility)continue;const def=FACILITIES[facility.key];const role=STAFF[member.key].role;if(role==='nurse'&&def.kind!=='support')facility.nursing+=2;if(role==='pharmacist')state.resources.medication+=facility.key==='pharmacy'?2:1;if(role==='surgeon'&&facility.key==='theatre')state.resources.surgery+=1}}

export function compatible(state,staffId,facilityId){const member=state.staff.find(s=>s.id===staffId);const facility=getFacility(state,facilityId);if(!member||!facility)return false;const role=STAFF[member.key].role;const def=FACILITIES[facility.key];if(!def.slots.includes(role))return false;return !state.staff.some(s=>s.id!==staffId&&s.facilityId===facilityId&&STAFF[s.key].role===role)}
export function assignStaff(state,staffId,facilityId){const member=state.staff.find(s=>s.id===staffId);if(!member||!compatible(state,staffId,facilityId))return false;const old=getFacility(state,member.facilityId);member.facilityId=facilityId;member.used=true;state.log.unshift(`${STAFF[member.key].name} moved from ${old?FACILITIES[old.key].name:'the staff pool'} to ${FACILITIES[getFacility(state,facilityId).key].name}. Their new assignment activates next round.`);return true}

export function investigate(state,patientId){const facility=patientFacility(state,patientId);const patient=facility?.patients.find(p=>p.id===patientId);if(!patient||patient.revealed)return false;const doctor=state.staff.find(s=>s.facilityId===facility.id&&STAFF[s.key].role==='doctor'&&!s.used);if(!doctor)return false;patient.revealed=true;doctor.used=true;state.log.unshift(`Patient ${patient.portrait} investigated in ${FACILITIES[facility.key].name}.`);return true}
export function treat(state,patientId,type){const facility=patientFacility(state,patientId);const patient=facility?.patients.find(p=>p.id===patientId);if(!patient?.revealed||!['nursing','medication','surgery'].includes(type))return false;const done=patient.completed[type]||0;if(done>=patient.needs[type])return false;if(type==='nursing'){if(facility.nursing<1||patient.nursingRound===state.round)return false;facility.nursing--;patient.nursingRound=state.round}else{if(state.resources[type]<1)return false;state.resources[type]--}patient.completed[type]=done+1;state.log.unshift(`${label(type)} provided to patient ${patient.portrait}.`);return true}
export function admit(state,patientId,targetId){const from=patientFacility(state,patientId);const target=getFacility(state,targetId);if(!from||from.key!=='ed'||!target||FACILITIES[target.key].kind!=='ward')return false;const patient=from.patients.find(p=>p.id===patientId);if(!patient?.revealed||target.patients.length>=FACILITIES[target.key].beds)return false;from.patients.splice(from.patients.indexOf(patient),1);target.patients.push(patient);if(target.key==='shortStay'&&patient.needs.nursing===1&&patient.completed.nursing===0)patient.completed.nursing=1;state.log.unshift(`Patient ${patient.portrait} admitted to ${FACILITIES[target.key].name}.`);return true}
export function discharge(state,patientId){const facility=patientFacility(state,patientId);const i=facility?.patients.findIndex(p=>p.id===patientId)??-1;if(i<0)return false;const p=facility.patients[i];const complete=Object.keys(p.needs).every(k=>(p.completed[k]||0)>=p.needs[k]);if(!p.revealed||!complete||(p.wardRequired&&facility.key==='ed'))return false;facility.patients.splice(i,1);state.money+=p.reward;state.reputation+=p.reputation;state.discard.push(p);state.log.unshift(`Patient ${p.portrait} discharged from ${FACILITIES[facility.key].name}: +$${p.reward}, +${p.reputation} reputation.`);return true}
export function buy(state,kind,key){const def=kind==='staff'?STAFF[key]:FACILITIES[key];if(!def||state.money<def.cost)return false;state.money-=def.cost;if(kind==='staff')addStaff(state,key);else addFacility(state,key);state.log.unshift(`${def.name} purchased for $${def.cost}.`);return true}
export function endRound(state){if(state.gameOver)return;deteriorate(state);state.round++;drawPatients(state,Math.min(2+Math.floor((state.round-1)/4),3));startRound(state);if(state.reputation<=0){state.gameOver=true;state.log.unshift('The hospital has lost public confidence.')}else state.log.unshift(`Round ${state.round} begins.`)}

function drawPatients(state,count){const ed=state.facilities.find(f=>f.key==='ed');for(let i=0;i<count;i++){if(!state.deck.length)break;if(ed.patients.length>=FACILITIES.ed.beds){state.reputation=Math.max(0,state.reputation-1);state.log.unshift('Emergency is full: an arriving patient was turned away. -1 reputation.');continue}const p=state.deck.shift();Object.assign(p,{revealed:false,completed:{nursing:0,medication:0,surgery:0},wait:0,deteriorations:0});ed.patients.push(p)}}
function deteriorate(state){for(const f of state.facilities)for(const p of [...f.patients]){if(!p.revealed)continue;p.wait++;if(p.wait>=p.deterioratesAfter){p.wait=0;p.deteriorations++;if(p.deteriorations>=2){f.patients.splice(f.patients.indexOf(p),1);state.reputation=Math.max(0,state.reputation-2);state.log.unshift(`Patient ${p.portrait} died. -2 reputation.`)}else{p.needs.nursing++;state.log.unshift(`Patient ${p.portrait} worsened and gained a Nursing Care need.`)}}}}
function label(x){return x[0].toUpperCase()+x.slice(1)}function shuffle(a,seed){let x=seed;for(let i=a.length-1;i>0;i--){x=(x*9301+49297)%233280;const j=Math.floor(x/233280*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
